import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<nav className={styles.mainnav}>
  <ul className="navlist">
<Link href="/"><a><li className="navitem">Home</li></a></Link>
<Link href="/about"><a><li className="navitem">About</li></a></Link>
<Link href="/blog"><a><li className="navitem">Blog</li></a></Link>
<Link href="/contact"><a><li className="navitem">Contact</li></a></Link>
  </ul>
</nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
         Welcome to Hunting Coder
        </h1>

        <p className={styles.description}>
          A Blog for Hunting Coders by Hunting Coders
        </p>
        <div className="blog">
          <h2>Popular Blogs</h2>
          <div className="blogitem">
<h3>How to learn javascript in 2022?</h3>
<p>javascript is a most popular programming language for building logics in a variety of Application (in web-browser)</p>
          </div>
          <div className="blogitem">
<h3>How to learn javascript in 2022?</h3>
<p>javascript is a most popular programming language for building logics in a variety of Application (in web-browser)</p>
          </div>
          <div className="blogitem">
<h3>How to learn javascript in 2022?</h3>
<p>javascript is a most popular programming language for building logics in a variety of Application (in web-browser)</p>
          </div>
          <div className="blogitem">
<h3>How to learn javascript in 2022?</h3>
<p>javascript is a most popular programming language for building logics in a variety of Application (in web-browser)</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
